name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependências
        run: npm install

      - name: Generate Prisma
        run: npx prisma generate

      - name: Compile
        run: npm run build

      - name: Tests
        run: npm test
