name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run backend tests (temporário)
      working-directory: ./backend
      run: |
        echo "⚠️ Backend tests não implementados ainda, ignorando..."
        exit 0

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run frontend tests (temporário)
      working-directory: ./frontend
      run: |
        echo "⚠️ Frontend tests não implementados ainda, ignorando..."
        exit 0

    - name: Deploy backend
      if: success()
      working-directory: ./backend
      run: echo "🚀 Deploy backend aqui"

    - name: Deploy frontend
      if: success()
      working-directory: ./frontend
      run: echo "🚀 Deploy frontend aqui"
